export enum ActionType {
	//// COMMON_ACTIONS

	GAME_RESET = 'COMMON_ACTIONS/GAME_RESET',
	FOCUS_CHANGED = 'COMMON_ACTIONS/FOCUS_CHANGED',

	//// ARENA ACTIONS
	SET_SIZE = 'ARENA/SET_SIZE',
	SET_COIN = 'ARENA/SET_COIN',
	FLUSH_COINS_BUFFER = 'ARENA/FLUSH_COINS_BUFFER',
	REMOVE_COIN = 'ARENA/REMOVE_COIN',
	SET_GAME_STATUS = 'ARENA/SET_GAME_STATUS',

	//// SNAKES ACTIONS

	SET_SNAKE = 'SNAKES/SET_SNAKE',
	REMOVE_SNAKE = 'SNAKES/REMOVE_SNAKE',
	SET_HEAD = 'SNAKES/SET_HEAD',
	SET_TAIL = 'SNAKES/SET_TAIL',
	NEW_DIRECTION = 'SNAKES/NEW_DIRECTION',

	//// BULLETS ACTIONS

	SET_BULLET = 'BULLETS/SET_BULLET',
	REMOVE_BULLET = 'BULLETS/REMOVE_BULLET',
	RESET_BULLETS = 'BULLETS/RESET_BULLETS',

	//// BIN ACTIONS

	MOVE_TO_BIN = 'BIN/MOVE_TO_BIN',
	EMPTY_BIN = 'BIN/EMPTY_BIN',

	//// STAT ACTIONS

	INC_SCORE = 'STAT/INC_SCORE',
	CHANGE_SCORE = 'STAT/CHANGE_SCORE',
	SET_WINNERS = 'STAT/SET_WINNERS',
	RESET_SCORE = 'STAT/RESET_SCORE',
	DEC_LIVES = 'STAT/DEC_LIVES',

	//// NOTIFS ACTIONS

	ADD_AUDIO_NOTIF = 'NOTIFS/ADD_AUDIO_NOTIF',
	REMOVE_AUDIO_NOTIF = 'NOTIFS/REMOVE_AUDIO_NOTIF',
	CLEAR_AUDIO_NOTIFS = 'NOTIFS/CLEAR_AUDIO_NOTIFS',
	ADD_VISUAL_NOTIF = 'NOTIFS/ADD_VISUAL_NOTIF',
	REMOVE_VISUAL_NOTIF = 'NOTIFS/REMOVE_VISUAL_NOTIF',
	CLEAR_VISUAL_NOTIFS = 'NOTIFS/CLEAR_VISUAL_NOTIFS',
	CLEAR_NOTIFS = 'NOTIFS/CLEAR_NOTIFS'
}
