export enum MessageType {
	// messages from client
	CREATE_ROOM = 'CLIENT/CREATE_ROOM',
	GET_AVAILABLE_ROOMS_LIST = 'CLIENT/GET_AVAILABLE_ROOMS_LIST',
	JOIN_ROOM = 'CLIENT/JOIN_ROOM',
	SET_SIZE = 'CLIENT/SET_SIZE',
	USER_INPUT = 'CLIENT/USER_INPUT',
	QUIT_ROOM = 'CLIENT/QUIT_ROOM',

	// messages from server
	CREATE_ROOM_SUCCESS = 'SERVER/CREATE_ROOM_SUCCESS',
	CREATE_ROOM_FAIL = 'SERVER/CREATE_ROOM_FAIL',
	JOIN_ROOM_SUCCESS = 'SERVER/JOIN_ROOM_SUCCESS',
	JOIN_ROOM_FAIL = 'SERVER/JOIN_ROOM_FAIL',
	ROOM_IS_READY = 'SERVER/ROOM_IS_READY',
	AVAILABLE_ROOMS_LIST = 'SERVER/AVAILABLE_ROOMS_LIST',
	GET_SIZE = 'SERVER/GET_SIZE',
	START = 'SERVER/START',
	TICK = 'SERVER/TICK',
	PLAYER_DISCONNECTED = 'SERVER/PLAYER_DISCONNECTED'
}
